### PR TITLE
Depend on aesara-base instead of aesara

### PR DESCRIPTION
**Pull request by maresb**
Blocking https://github.com/conda-forge/pymc-feedstock/pull/49

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
## Warning

This has the unfortunate side-effect going forward of effectively pinning `aesara >=2.7.4` since the `aesara-base` package doesn't exist otherwise.

Note that build 0 will still be solvable even after build 1 becomes available. Thus `conda install -c conda-forge aeppl aesara<2.7.4` will still work and install aeppl `0.0.31`. But once `0.0.32` comes out, the above command will only continue to work with `0.0.31`.

Is this a problem?

**Comment by maresb** [comment]
Or should we adopt the dual-output model here as well? (`aeppl-base` + `aeppl`)

**Comment by twiecki** [comment]
> Or should we adopt the dual-output model here as well? (aeppl-base + aeppl)

I think that's the only way, otherwise people who'd just install `aeppl` wouldn't get compilers :-/.

**Comment by maresb** [comment]
Superseded by #30

**Pull request closed without merging**
